### ISSUE TITLE
use package in node.js

### ISSUE THREAD

**Issue by ajax484** [chrisDeFouRire/bmerch#1]
i noticed that the package is written in esm, i'd like to use it in my node.js app, i use commonjs require statements

**Comment by chrisDeFouRire** [comment]
If you're still using commonjs, you could use the dynamic import feature...

```
const bmerch = import('bmerch');
bmerch.then( ({BinanceMerch}) => {
const binanceMerch = new BinanceMerch(apikey, apisecret, { timeout: 5000 })
})
```

That should do the trick (but forces you to account for the async import)

**Comment by ajax484** [comment]
Awesome, thanks so much
