### ISSUE TITLE
Webhook

### ISSUE THREAD

**Issue by jorgehenriquezd** [chrisDeFouRire/bmerch#2]
Hey thanks for this library, I already can create payment orders! 

this is not an issue but I don't know how to get the data and headers that a have to pass to the webhook. Can you help me please?

**Comment by chrisDeFouRire** [comment]
Hi! maybe you'll find more information in Dojibar, the project I've written bmerch for.... 
see https://github.com/chrisDeFouRire/dojibar/blob/main/src/binanceWebhook.ts for how I'm using the data sent by Binance received in the webhook.

Here's the webhook documentation from Binance: https://developers.binance.com/docs/binance-pay/order-notification
